### ISSUE TITLE
Should Request use Headers

### ISSUE THREAD

**Issue by paganotoni** [markbates/willie#1]
Hey @markbates  i'm liking willie, thanks for it! 

I'm working on a test scenario composed on 2 request where the second request handler should use  one header set on the first response

I'm doing something like:

```go
...
	a.GET("/set", func(c Context) error {
		c.Flash().Add("errors", "Error AJ set")
		c.Flash().Add("errors", "Error DAL set")

		return nil
	})

	a.GET("/", func(c Context) error {
		return c.Render(201, rr.HTML(tempFolder+"show.html"))
	})

	w := willie.New(a)
	res := w.Request("/set").Get()

	w.Headers["Cookie"] = res.Header().Get("Set-Cookie")
	res = w.Request("/").Get()

	r.Contains(res.Body.String(), "Error AJ set")
	r.Contains(res.Body.String(), "Error DAL set")

	w.Headers["Cookie"] = res.Header().Get("Set-Cookie")
	res = w.Request("/").Get()
...
```

i trying to manually set the cookie field by using:

```go
	w.Headers["Cookie"] = res.Header().Get("Set-Cookie")
```

but seems not the correct way to do it, is there a way to do it ? would you be accepting PR's to support this kind of header manipulation ?

**Comment by markbates** [comment]
In this case cookies should already be held across requests, that's how sessions work. :)
